#!/bin/sh

# A wrapper around minimesos installer script.

command_exists() {
    command -v "$@" > /dev/null 2>&1
}

if ! command_exists curl; then
    echo "Please install curl to fetch the minimesos files"
    exit 1
fi

# invoking versioned installation script
SCRIPT_PATH=https://raw.githubusercontent.com/ContainerSolutions/minimesos/master/bin/install

httpcode=$(curl -s -o /dev/null -I -w '%{http_code}' --max-time 1 $SCRIPT_PATH || echo "404" )
if [ $httpcode -eq 200 ]; then
    curl -s $SCRIPT_PATH | sh
else
    echo "Failed to pull installer off github.com (http err: ${httpcode}), please try again."
    exit 1
fi

exit 0
